### ISSUE TITLE
Metadata version mismatch when build or start app

### ISSUE THREAD

**Issue by Belouccio** [MurhafSousli/ngx-scrollbar#15]
When i try to start my app via ng serve I get this error:
```
ERROR in Error: Metadata version mismatch for module /home/developer/projects/corpsite/node_modules/ngx-scrollbar/ngx-scrollbar.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/home/developer/projects/corpsite/node_modules/@angular/compiler/bundles/compiler.umd.js:25616:34)
    at StaticSymbolResolver._createSymbolsOf (/home/developer/projects/corpsite/node_modules/@angular/compiler/bundles/compiler.umd.js:25404:46)
    at StaticSymbolResolver.getSymbolsOf (/home/developer/projects/corpsite/node_modules/@angular/compiler/bundles/compiler.umd.js:25385:14)
    at /home/developer/projects/corpsite/node_modules/@angular/compiler/bundles/compiler.umd.js:24241:30
    at Array.forEach (native)
    at extractProgramSymbols (/home/developer/projects/corpsite/node_modules/@angular/compiler/bundles/compiler.umd.js:24240:79)
    at AotCompiler.analyzeModulesAsync (/home/developer/projects/corpsite/node_modules/@angular/compiler/bundles/compiler.umd.js:23796:47)
    at CodeGenerator.codegen (/home/developer/projects/corpsite/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/home/developer/projects/corpsite/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (/home/developer/projects/corpsite/node_modules/@ngtools/webpack/src/plugin.js:386:44)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
my nodejs version 8.1.4
npm 5.3.0
my package.json file

```
"dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "animejs": "^2.2.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "ng2-scroll-to": "^1.0.7",
    "ng2-semantic-ui": "^0.9.6",
    "ngx-carousel": "^1.3.5",
    "ngx-gallery": "^4.3.0",
    "ngx-scrollbar": "^1.5.5",
    "ngx-slick": "^0.1.3",
    "ngx-wow": "^1.0.2",
    "node-sass": "^4.7.2",
    "postcss-loader": "^2.0.9",
    "rxjs": "^5.4.2",
    "sass-loader": "^6.0.6",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.4",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/gsap": "^1.19.1",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.2.18",
    "@types/node": "~6.0.60",
    "@types/vivus": "^0.4.0",
    "autoprefixer": "^6.5.3",
    "circular-dependency-plugin": "^3.0.0",
    "codelyzer": "~3.2.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.1",
    "cssnano": "^3.10.0",
    "exports-loader": "^0.6.3",
    "file-loader": "^0.10.0",
    "flickity": "^2.0.10",
    "gsap": "^1.20.3",
    "gulp": "github:gulpjs/gulp#4.0",
    "html-webpack-plugin": "^2.29.0",
    "istanbul-instrumenter-loader": "^2.0.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "less-loader": "^4.0.5",
    "postcss-loader": "^1.3.3",
    "postcss-url": "^5.1.2",
    "protractor": "~5.1.2",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.3",
    "source-map-loader": "^0.2.0",
    "style-loader": "^0.13.1",
    "stylus-loader": "^3.0.1",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "^2.4.2",
    "url-loader": "^0.5.7",
    "webpack": "~3.5.5",
    "webpack-concat-plugin": "1.4.0",
    "webpack-dev-server": "~2.7.1"
  }
```
I found a solution to update my angular from 4 to 5, but I don't want to do that. Can I fix it without updating angular? Thank you

**Comment by MurhafSousli** [comment]
@Belouccio Unfortunately, you need to update to Angular 5
