### ISSUE TITLE
Build Error - Angular 9.1.1

### ISSUE THREAD

**Issue by scottie6** [MurhafSousli/ngx-scrollbar#304]
```
Compiling ngx-scrollbar/smooth-scroll : module as esm5
Warning: Invalid constructor parameter decorator in /Users/seanross/dev/deets/deetsprem-admin-web/node_modules/ngx-scrollbar/fesm2015/ngx-scrollbar-smooth-scroll.js:
 () => [
    { type: undefined, decorators: [{ type: Inject, args: [DOCUMENT,] }] },
    { type: Object, decorators: [{ type: Inject, args: [PLATFORM_ID,] }] },
    { type: undefined, decorators: [{ type: Optional }, { type: Inject, args: [SMOOTH_SCROLL_OPTIONS,] }] }
]
Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected SmoothScrollManager to have an inner class declaration
    at Esm5ReflectionHost.getInternalNameOfClass (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/@angular/compiler-cli/ngcc/src/host/esm5_host.js:88:23)
    at DelegatingReflectionHost.getInternalNameOfClass (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/@angular/compiler-cli/ngcc/src/host/delegating_host.js:89:34)
    at extractInjectableMetadata (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/injectable.js:125:69)
    at InjectableDecoratorHandler.analyze (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/injectable.js:66:24)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:345:40)
    at analyze (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:297:58)
    at _loop_1 (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:319:21)
    at NgccTraitCompiler.TraitCompiler.analyzeClass (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:325:35)
    at NgccTraitCompiler.analyzeFile (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/@angular/compiler-cli/ngcc/src/analysis/ngcc_trait_compiler.js:47:26)
    at DecorationAnalyzer.analyzeProgram (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:134:39)
    at ClusterMaster.onWorkerMessage (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:166:27)
    at /Users/seanross/dev/deets/deetsprem-admin-web/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:50:95
    at ClusterMaster.<anonymous> (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:246:57)
    at step (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/tslib/tslib.js:139:27)
    at Object.next (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/tslib/tslib.js:120:57)
    at /Users/seanross/dev/deets/deetsprem-admin-web/node_modules/tslib/tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/tslib/tslib.js:109:16)
    at EventEmitter.<anonymous> (/Users/seanross/dev/deets/deetsprem-admin-web/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:240:32)
    at EventEmitter.emit (events.js:209:13)
An unhandled exception occurred: NGCC failed.
See "/private/var/folders/f3/jx_1sn3132n880g4z5gd0nj40000gn/T/ng-Vab7pO/angular-errors.log" for further details.
```
- Angular: 9.1.1
- ngx-scrollbar: 7.3.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by HitendraSinghRathore** [comment]
Facing the same issue with angular 9.1.2 and scrollbar version - 7.3.0

**Comment by MurhafSousli** [comment]
I think this is a typescript version issue, try to angular upgrade to latest version, or use v7.2.3
