### ISSUE TITLE
Ng scroll bar error

### ISSUE THREAD

**Issue by avanishtcoders** [MurhafSousli/ngx-scrollbar#442]
I have upgraded angular from version 8 to 9. Angular app getting serve but with ng scroll bar errors at console>

ngx-scrollbar.d.ts.NgScrollbar.html:17 ERROR TypeError: Cannot read properties of undefined (reading 'getElementRef')
    at NgScrollbar.get [as view] (ngx-scrollbar.js:416:1)
    at NgScrollbar.push../node_modules/ngx-scrollbar/fesm5/ngx-scrollbar.js.NgScrollbar.showScrollbarY (ngx-scrollbar.js:467:1)
    at Object.updateRenderer (ngx-scrollbar.d.ts.NgScrollbar.html:19:68)
    at Object.debugUpdateRenderer [as updateRenderer] (core.js:32129:1)
    at checkAndUpdateView (core.js:31501:1)
    at callViewAction (core.js:31737:1)
    at execEmbeddedViewsAction (core.js:31700:1)
    at checkAndUpdateView (core.js:31497:1)
    at callViewAction (core.js:31737:1)
    at execComponentViewsAction (core.js:31679:1)
    
    
    please help on this. Anything you need from my side please ask

**Comment by avanishtcoders** [comment]
> I have upgraded angular from version 8 to 9. Angular app getting serve but with ng scroll bar errors at console>
> 
> ngx-scrollbar.d.ts.NgScrollbar.html:17 ERROR TypeError: Cannot read properties of undefined (reading 'getElementRef') at NgScrollbar.get [as view] (ngx-scrollbar.js:416:1) at NgScrollbar.push../node_modules/ngx-scrollbar/fesm5/ngx-scrollbar.js.NgScrollbar.showScrollbarY (ngx-scrollbar.js:467:1) at Object.updateRenderer (ngx-scrollbar.d.ts.NgScrollbar.html:19:68) at Object.debugUpdateRenderer [as updateRenderer] (core.js:32129:1) at checkAndUpdateView (core.js:31501:1) at callViewAction (core.js:31737:1) at execEmbeddedViewsAction (core.js:31700:1) at checkAndUpdateView (core.js:31497:1) at callViewAction (core.js:31737:1) at execComponentViewsAction (core.js:31679:1)
> 
> ```
> please help on this. Anything you need from my side please ask
> ```

you don't know its answer ? How to fix

**Comment by MurhafSousli** [comment]
You are using an old version of Angular, either upgrade to the latest Angular version or look into the [changelog](https://github.com/MurhafSousli/ngx-scrollbar/blob/master/CHANGELOG.md#723) and find a compatible version with Angular 9 (Try `ngx-scrollbar@7.2.3`).

I closed your issue because you didn't fill the template issue properly!

**Comment by Anjanalachu** [comment]
NgScrollbar.html:17 
 ERROR 
TypeError: Cannot read properties of undefined (reading 'getElementRef')
    at get view (ngx-scrollbar.js:365:1)
    at NgScrollbar.showScrollbarY (ngx-scrollbar.js:398:1)
    at Object.eval [as updateRenderer] (NgScrollbar.html:19:21)
    at Object.debugUpdateRenderer [as updateRenderer] (core.js:31332:1)
    at checkAndUpdateView (core.js:30710:1)
    at callViewAction (core.js:30946:1)
    at execEmbeddedViewsAction (core.js:30909:1)
    at checkAndUpdateView (core.js:30706:1)
    at callViewAction (core.js:30946:1)
    at execComponentViewsAction (core.js:30888:1) i have this error when I changed from angular 9 to 10 my  "ngx-scrollbar": "^4.2.0", ,please help me to solve this error
